; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32dev]
; Platform version ko 6.5.0 (ESP32 Arduino Core 2.0.14) par lock kiya gaya hai
; Ye standard Ethernet library aur production stability ke liye best hai
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

; Serial Monitor speed
monitor_speed = 115200

; Download standard Ethernet library automatically
lib_deps = 
    arduino-libraries/Ethernet @ ^2.0.2